### PR TITLE
macOS fixes

### PR DESCRIPTION
**Pull request by ra1nb0w**
- rigctl.c: SOL_TCP is undefined on macOS
- Makefile.mac: add subrx and css

### CODE REVIEW

**Comment by ra1nb0w** [comment]
Just a sidenote:
```
rigctl.c:3968:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
```

**Comment by kgarrels** [comment]
I think the SOL_TCP thing is dubious: SO_LINGER should also belong to SOL_SOCKET. I played with both versions and found no difference in behaviour.

**Comment by ra1nb0w** [comment]
@kgarrels what do you mean exactly?

**Comment by kgarrels** [comment]
Ups...,I checked again, mistake on my side.
Can I delete my post?
:)

**Comment by ra1nb0w** [comment]
don't worry; you wrote about the mistake.

**Pull request closed without merging**
